############################################################
# Dockerfile for Twitter Frontend
# Based on nginx
############################################################

# Set the base image to Debian
FROM nginx

# File Author / Maintainer
MAINTAINER Bogdan Alexandru Melinte <bogdan.melinte@hotmail.com>

# Copy files
COPY dist/ /usr/share/nginx/html
