############################################################
# Dockerfile for Twitter PHP
# Based on mileschou/phalcon:fpm
############################################################

# Set the base image to mileschou/phalcon:fpm
FROM mileschou/phalcon:fpm

# File Author / Maintainer
MAINTAINER Bogdan Alexandru Melinte <bogdan.melinte@hotmail.com>

# Install PDO MYSQL
RUN docker-php-ext-install pdo pdo_mysql
